name: Build Magisk Module Zip

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (nëse është e nevojshme)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (nëse është e nevojshme)
        run: |
          # Shtoni komandat për instalimin e varësive të nevojshme
          # Për shembull:
          # pip install -r requirements.txt
          echo "No dependencies to install."

      - name: Create zip archive
        run: |
          zip -r Odex_app.zip ./* -x '.git/*' '.github/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Odex_app
          path: Odex_app.zip

      - name: Create Release and Upload Zip (Opsionale)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Odex_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
