name: Build Magisk Module Zip

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      upload_release:
        description: 'A dëshironi të ngarkoni zip-in në një release të re?'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no
      version:
        description: 'Versioni i ri i modulës'
        required: false
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (nëse është e nevojshme)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (nëse është e nevojshme)
        run: |
          echo "No dependencies to install."

      - name: Create zip archive
        run: |
          zip -r Odex_app.zip ./* -x '.git/*' '.github/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Odex_app
          path: Odex_app.zip

      - name: Determine if should upload to release
        id: should_upload
        run: |
          echo "UPLOAD_RELEASE=${{ github.event.inputs.upload_release || 'no' }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.event.inputs.version || 'latest' }}" >> $GITHUB_ENV

      - name: Debugging Info
        run: |
          echo "UPLOAD_RELEASE=${{ env.UPLOAD_RELEASE }}"
          echo "VERSION=${{ env.VERSION }}"
          echo "GITHUB_REF=${{ github.ref }}"

      - name: Create Release and Upload Zip
        if: env.UPLOAD_RELEASE == 'yes' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION || github.ref }}
          release_name: Release ${{ env.VERSION || github.ref }}
          files: Odex_app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
